### ISSUE TITLE
Does it work with react-router?

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/picker#1]
@StorytellerCZ 
Does it work with react-router?
Of course, if 404 pages are set in react-router

**Comment by StorytellerCZ** [comment]
It should work, or more precisely picker will check first and if it is going to a page defined in Picker it will execute the code for that page. If it doesn't find any match then it goes on to the client side and it doesn't matter what router you have there. I'm also thinking that in theory you could have routes defined both on client and in Picker and it would work as long as you would not respond to the request.

**Comment by Saeeed-B** [comment]
its good and work , thank you
